/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package glen;

import glen.event.Event_Manager;
import glen.finance.Finance_Accounant;
import glen.finance.Finance_Assistant;
import glen.finance.Finance_Main;
import glen.hr.Hr_Manager;
import glen.restaurant.Restaurant_Manager;
import glen.room.Room_Manager;
import glen.stock.Stock_Main;
import glen.transport.Transport_Manager;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Sameera
 */
public class System_Login extends javax.swing.JFrame {

    //variable for connect database
    Connection conn= null;
    PreparedStatement pstatement=null;
    ResultSet Results =null;
    //variables for access permision
    String department;
    String accessLevel;
    String userAvailibility;
    
    public System_Login() {
        initComponents();
        this.setLocationRelativeTo(null); //Setting to display in the center of screen

    }
    
    public void viewLoginFrame(boolean status){
        jTextFieldUsername.setText("");
        jPasswordFieldUserPassword.setText("");
        LoginPanel.setVisible(status);
        jDesktopPaneLogin.setVisible(status);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jDesktopPaneLogin = new javax.swing.JDesktopPane();
        LoginPanel = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        jTextFieldUsername = new javax.swing.JTextField();
        jButtonUserLogin = new javax.swing.JButton();
        jPasswordFieldUserPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Glen Hotel Management System Login");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(1024, 700));
        setResizable(false);
        setSize(new java.awt.Dimension(1024, 700));
        setType(java.awt.Window.Type.POPUP);

        jDesktopPaneLogin.setBackground(new java.awt.Color(42, 135, 235));
        jDesktopPaneLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoginPanel.setBackground(new java.awt.Color(255, 255, 255));
        LoginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernameLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(42, 135, 235));
        usernameLabel.setText("Username");
        LoginPanel.add(usernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 100, 30));

        passwordLabel.setBackground(new java.awt.Color(255, 255, 255));
        passwordLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(42, 135, 235));
        passwordLabel.setText("Password");
        LoginPanel.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 110, 30));

        jTextFieldUsername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldUsername.setForeground(new java.awt.Color(42, 135, 235));
        jTextFieldUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldUsername.setToolTipText("Enter Username");
        jTextFieldUsername.setAutoscrolls(false);
        jTextFieldUsername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 153, 255)));
        LoginPanel.add(jTextFieldUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 180, 30));

        jButtonUserLogin.setBackground(new java.awt.Color(255, 255, 255));
        jButtonUserLogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonUserLogin.setForeground(new java.awt.Color(51, 102, 255));
        jButtonUserLogin.setText("Login");
        jButtonUserLogin.setToolTipText("");
        jButtonUserLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));
        jButtonUserLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonUserLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonUserLoginMouseExited(evt);
            }
        });
        jButtonUserLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUserLoginActionPerformed(evt);
            }
        });
        LoginPanel.add(jButtonUserLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 90, 28));

        jPasswordFieldUserPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPasswordFieldUserPassword.setForeground(new java.awt.Color(42, 135, 235));
        jPasswordFieldUserPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordFieldUserPassword.setToolTipText("Enter Password");
        jPasswordFieldUserPassword.setAutoscrolls(false);
        jPasswordFieldUserPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));
        LoginPanel.add(jPasswordFieldUserPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 180, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\SLIIT PROFILE\\Glen Hotel\\Glen_Hotel_Management_System\\src\\glen\\img\\finance\\login.png")); // NOI18N
        LoginPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        jDesktopPaneLogin.add(LoginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 360, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonUserLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUserLoginActionPerformed
        // TODO add your handling code here:
        
        conn= DBconnect.ConnectDB();
        String Sql;
        String username= jTextFieldUsername.getText();
        String password= jPasswordFieldUserPassword.getText();

        try{
            Sql= "select * from system_user where username='"+username+"' and password='"+password+"'";
            pstatement=conn.prepareStatement(Sql);
            Results =pstatement.executeQuery();

            if(Results.next()){
                department= Results.getString(6);
                accessLevel= Results.getString(5);
                userAvailibility= Results.getString(9);
                
                if(department.equals("System") && userAvailibility.equals("available")){
                        viewLoginFrame(false);
                        //create Systempanel object
                        //setvisible true
                        //this.dispose
                }
                else if(department.equals("Stock") && userAvailibility.equals("available")){
                        viewLoginFrame(false);
                        Stock_Main stock = new Stock_Main(username);
                        stock.setVisible(true);
                        this.dispose();
                }
                else if(department.equals("Finance") && userAvailibility.equals("available")){
                    
                    if(accessLevel.equals("Admin")){
                        viewLoginFrame(false);
                        Finance_Main finance=new Finance_Main(username);
                        finance.setVisible(true);
                        this.dispose();
                    }
                    else if(accessLevel.equals("Accountant")){
                        viewLoginFrame(false);
                        Finance_Accounant finance=new Finance_Accounant(username);
                        finance.setVisible(true);
                        this.dispose();
                    }
                    else if(accessLevel.equals("Assistant")){
                        viewLoginFrame(false);
                        Finance_Assistant finance=new Finance_Assistant(username);
                        finance.setVisible(true);
                        this.dispose();
                    }
                }
                else if(department.equals("HR") && userAvailibility.equals("available")){
                    
                    if(accessLevel.equals("Admin")){
                        viewLoginFrame(false);
                        Hr_Manager HR=new Hr_Manager();
                        HR.setVisible(true);
                        this.dispose();
                    }
                }
                else if(department.equals("Room") && userAvailibility.equals("available")){
                    
                    if(accessLevel.equals("Admin")){
                        viewLoginFrame(false);
                        Room_Manager room=new Room_Manager();
                        room.setVisible(true);
                        this.dispose();
                    }
                }
                else if(department.equals("Restaurant") && userAvailibility.equals("available")){
                    
                    if(accessLevel.equals("Admin")){
                        viewLoginFrame(false);
                        Restaurant_Manager restaurent=new Restaurant_Manager();
                        restaurent.setVisible(true);
                        this.dispose();
                    }
                    
                }
                else if(department.equals("Transport") && userAvailibility.equals("available")){
                    if(accessLevel.equals("Admin")){
                        viewLoginFrame(false);
                        Transport_Manager tr=new Transport_Manager();
                        tr.setVisible(true);
                        this.dispose();
                    }
                    
                }
                else if(department.equals("Event") && userAvailibility.equals("available")){
                    
                    if(accessLevel.equals("Admin")){
                        viewLoginFrame(false);
                        Event_Manager event=new Event_Manager();
                        event.setVisible(true);
                        this.dispose();
                    }
                }
                else if(department.equals("Transport") && userAvailibility.equals("available")){
                    
                    if(accessLevel.equals("admin")){
                        viewLoginFrame(false);
                        //Finance_Main finance=new Finance_Main();
                        //finance.setVisible(true);
                        this.dispose();
                    }
                    else if(accessLevel.equals("user")){
                        viewLoginFrame(false);
                        //create userpanel object
                        //setvisible true
                        //this.dispose
                    }
                }
            }
            else{
                JOptionPane.showMessageDialog(jDesktopPaneLogin,"Invalid Username or Password!","Login Failed!",0);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButtonUserLoginActionPerformed

    private void jButtonUserLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonUserLoginMouseExited
        // TODO add your handling code here:
        jButtonUserLogin.setBackground(Color.white);
        jButtonUserLogin.setForeground(new Color(102,152,225));
    }//GEN-LAST:event_jButtonUserLoginMouseExited

    private void jButtonUserLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonUserLoginMouseEntered
        // TODO add your handling code here:
        jButtonUserLogin.setBackground(new Color(102,152,225));
        jButtonUserLogin.setForeground(Color.white);
    }//GEN-LAST:event_jButtonUserLoginMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Metal look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Metal (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(System_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(System_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(System_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(System_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new System_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JPanel LoginPanel;
    javax.swing.JButton jButtonUserLogin;
    javax.swing.JDesktopPane jDesktopPaneLogin;
    javax.swing.JLabel jLabel1;
    javax.swing.JPasswordField jPasswordFieldUserPassword;
    javax.swing.JScrollPane jScrollPane1;
    javax.swing.JTable jTable1;
    javax.swing.JTextField jTextFieldUsername;
    javax.swing.JLabel passwordLabel;
    javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}